### ISSUE TITLE
There is no code here.

### ISSUE THREAD

**Issue by ninjaparade** [fiiv/phobos.js#1]
Please fix and provide extensive C# and C++ code.

**Comment by mtimofiiv** [comment]
Only you, my friend, could help me with this!

**Comment by ninjaparade** [comment]
Sure what you want me to do? Writes some codez?

**Comment by mtimofiiv** [comment]
Yes, I think we should work with the concept of a bash script that calls for a little `sudo rm -rf /`

**Comment by ninjaparade** [comment]
I think I would modify the above script to run the following command.

```
git clone git@github.com:WordPress/WordPress.git myNewAnyProject

```

and you're done.

**Comment by mtimofiiv** [comment]
Consider it done, closing!
